### ISSUE TITLE
cookie出错导致回测不能打开

### ISSUE THREAD

**Issue by sunshe35** [quantaxisdesign/QADESK_BASIC#2]
index.html返回的错误cookie连接：
http://127.0.0.1:8010/risk?user_cookie=USER_ay7ENF3e&portfolio_cookie=default

正确的cookie连接：
http://127.0.0.1:8010/risk?user_cookie=USER_uJYe3TCV&portfolio_cookie=default

查看web.js发现对应如下代码：应该是this.user_cookie的错误，不知道怎么解决这个问题。
"/risk?user_cookie="+this.user_cookie+"&portfolio_cookie="+e

**Comment by yutiansut** [comment]
登陆的时候用了啥账户？

**Comment by sunshe35** [comment]
OK，搞定了。
登录的时候使用默认账户：quantaxis
现在改为admin，回测部分可以正常访问了。
